

# shows the help
def show_help():
	print("This game has 3 playing options")
	print("single player - play against the computer")
	print("multi-player - creates a new game")
	print("\t\t the player selects how many players will be in the game ")
	print("\t\t selects his/her team")
	print("\t\t waits for other players to join the new 'open' game")
	print("\t\t if in 1 minute the game still need player, then ")
	print("\t\t the players are sent back to the main menu ")
	print("join - the player select among the 'open' games")
	print("\t\t select the team to play with ")
	print("\t\t wait for others players to join the required positions ")
	print("See status -  is to get the win,lost and quit games")
	print("Quit the game ")
	print("================================================")
	print("To connect to the chat the player needs to run the file 'clientchat.py'")
	print("which is in the same directory of the client application ")
	print("this application will ask for a code (initially) ")
	print("de code asked, is given when the client is run (is a number)")
	print("is announced this way: 'If you want to use the chat use this code: ####' ")
	print("enter that code and your clientchat will be ready")
	print("\t\t to send message to specific audience use these option at the beginning of the line")
	print("\t\t -p -player message for specific player example: -p -bob hello bob!!")
	print("\t\t -t message for the teammates example: -t Lets beat them all!!!")
	print("\t\t -g message for the players in the current game: -g It was a ")
	print("\t\t pleasure play with all of you guys")
	print("\t\t no prefix will be directed for all the connected players in the server ")
	print("\t\t example: Hi guys, this game was done using python! ")
	input("Press press enter...")